<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit05cc358fbc48b1d2e490be83fb91cbaa
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'Ejs\\MakePage\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ejs\\MakePage\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit05cc358fbc48b1d2e490be83fb91cbaa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit05cc358fbc48b1d2e490be83fb91cbaa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit05cc358fbc48b1d2e490be83fb91cbaa::$classMap;

        }, null, ClassLoader::class);
    }
}
